version: "2"
 
services:
    influxdb:
        image: influxdb:1.8
        restart: always
        container_name: influxdb
        ports:
          - "8086:8086"
          - "8083:8083"
        volumes:
          - ./var/docker/data/influxdb:/var/lib/influxdb:cached
        environment:
          - INFLUXDB_DB='loadTestingDB'
          - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
          - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        hostname: grafana
        restart: always
        ports:
            - "3000:3000"
        environment:
          - GF_SERVER_DOMAIN=docker.for.mac.localhost:3000
          - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
          - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}